# Generated by Django 3.2 on 2022-02-12 09:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancy',
            name='another_description',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='consultancy',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='design_engineering',
            name='another_description',
        ),
        migrations.RemoveField(
            model_name='design_engineering',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='design_engineering',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project_management',
            name='another_description',
        ),
        migrations.RemoveField(
            model_name='project_management',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='project_management',
            name='short_description',
        ),
        migrations.AddField(
            model_name='consultancy',
            name='icon',
            field=models.FileField(blank=True, help_text='please upload svg icon', null=True, upload_to='consultancy_imgs'),
        ),
        migrations.AddField(
            model_name='design_engineering',
            name='icon',
            field=models.ImageField(blank=True, help_text='please upload svg icon', null=True, upload_to='consultancy_imgs'),
        ),
        migrations.AddField(
            model_name='project_management',
            name='icon',
            field=models.ImageField(blank=True, help_text='please upload svg icon', null=True, upload_to='consultancy_imgs'),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='try not to put very large text', null=True),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='title',
            field=models.CharField(help_text='title must be in 255 character', max_length=255),
        ),
        migrations.AlterField(
            model_name='design_engineering',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='try not to put very large text', null=True),
        ),
        migrations.AlterField(
            model_name='design_engineering',
            name='title',
            field=models.CharField(help_text='title must be in 255 character', max_length=255),
        ),
        migrations.AlterField(
            model_name='project_management',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='try not to put very large text', null=True),
        ),
        migrations.AlterField(
            model_name='project_management',
            name='title',
            field=models.CharField(help_text='title must be in 255 character', max_length=255),
        ),
    ]
