# Generated by Django 3.2 on 2022-03-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20220212_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_engineering',
            name='icon',
            field=models.FileField(blank=True, help_text='please upload svg icon', null=True, upload_to='design_engineering'),
        ),
        migrations.AlterField(
            model_name='project_management',
            name='icon',
            field=models.FileField(blank=True, help_text='please upload svg icon', null=True, upload_to='project_management'),
        ),
    ]
