# Generated by Django 3.2 on 2022-03-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('LN', 'Landmark'), ('RN', 'Running'), ('UP', 'Upcoming'), ('CO', 'Complated')], max_length=2, null=True),
        ),
    ]
