# Generated by Django 3.2 on 2022-03-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_auto_20220310_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='icon',
            field=models.FileField(blank=True, help_text='please upload svg icon', null=True, upload_to='Scope_images'),
        ),
    ]
